export const EmailsTemplate = [
  {
    name: 'Welcome',
    subject: 'Welcome #user.name#',
    body: `<!DOCTYPE html><html><head><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#333;background-color:#f9f9f9;margin:0;padding:0}.container{max-width:600px;margin:20px auto;background:#fff;padding:20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1)}.header{text-align:center;background-color:#4CAF50;color:white;padding:10px 0;border-radius:8px 8px 0 0}.header h1{margin:0;font-size:24px}.content{padding:20px}.content p{margin:10px 0}.content a{display:inline-block;margin:20px 0;padding:10px 20px;background-color:#4CAF50;color:white;text-decoration:none;border-radius:4px}.footer{text-align:center;margin-top:20px;font-size:12px;color:#666}</style></head><body><div class='container'><div class='header'><h1>Welcome to Our Service!</h1></div><div class='content'><p>Hi #user.name#,</p><p>We're excited to have you on board! Thank you for joining us. You can now explore all the amazing features we have to offer.</p><p>To get started, please click the button below:</p><a href='https://example.com/get-started' target='_blank'>Get Started</a><p>If you have any questions, feel free to reach out to our support team.</p><p>Cheers,</p><p>The Team</p></div><div class='footer'><p>&copy; 2024 Our Company. All rights reserved.</p></div></div></body></html>`
  },
  {
    name: 'Password Reset',
    subject: 'Password Reset',
    body: '<!DOCTYPE html><html><head><style>body{font-family:Arial,sans-serif;margin:0;padding:0;}h1{color:#FF5722;}p{color:#555;}</style></head><body><h1>Password Reset Request</h1><p>Hello #user.name#, click <a href="#reset.link#" style="color:#FF5722;text-decoration:none;">here</a> to reset your password. This link is valid for 24 hours.</p></body></html>',
  },
  {
    name: 'Subscription Confirmation',
    subject: 'Subscription Confirmation',
    body: '<!DOCTYPE html><html><head><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#333;background-color:#f9f9f9;margin:0;padding:0}.container{max-width:600px;margin:20px auto;background:#fff;padding:20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1)}.header{text-align:center;background-color:#2196F3;color:white;padding:10px 0;border-radius:8px 8px 0 0}.header h1{margin:0;font-size:24px}.content{padding:20px}.content p{margin:10px 0}.footer{text-align:center;margin-top:20px;font-size:12px;color:#666}</style></head><body><div class="container"><div class="header"><h1>Subscription Confirmed</h1></div><div class="content"><p>Hi #user.name#,</p><p>Thank you for subscribing to our service. Your subscription is now active.</p><p>Enjoy all the benefits we have to offer.</p><p>If you have any questions, feel free to reach out to our support team.</p><p>Best regards,</p><p>The Subscription Team</p></div><div class="footer"><p>&copy; 2024 Our Company. All rights reserved.</p></div></div></body></html>',
  },
  {
    name: 'Christmas Offers',
    subject: 'Christmas Offers waiting for you #user.name#',
    body: '<!DOCTYPE html><html><head><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#333;background-color:#f9f9f9;margin:0;padding:0}.container{max-width:600px;margin:20px auto;background:#fff;padding:20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1)}.header{text-align:center;background-color:#FF0000;color:white;padding:10px 0;border-radius:8px 8px 0 0}.header h1{margin:0;font-size:24px}.content{padding:20px}.content p{margin:10px 0}.content a{display:inline-block;margin:20px 0;padding:10px 20px;background-color:#FF0000;color:white;text-decoration:none;border-radius:4px}.footer{text-align:center;margin-top:20px;font-size:12px;color:#666}</style></head><body><div class="container"><div class="header"><h1>Christmas Offers Just for You!</h1></div><div class="content"><p>Hi #user.name#,</p><p>The holiday season is here, and so are our exclusive Christmas offers! Enjoy discounts up to 50% on our premium products.</p><p>Don\'t miss out! These offers are valid until December 25th.</p><a href="#christmas.offers.link#" target="_blank">Browse Offers</a><p>Happy Holidays!</p><p>The Team</p></div><div class="footer"><p>&copy; 2024 Our Company. All rights reserved.</p></div></div></body></html>',
  },
  {
    name: 'Monthly Newsletter',
    subject: 'Monthly Newsletter',
    body: '<!DOCTYPE html><html><head><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#333;background-color:#f9f9f9;margin:0;padding:0}.container{max-width:600px;margin:20px auto;background:#fff;padding:20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1)}.header{text-align:center;background-color:#3F51B5;color:white;padding:10px 0;border-radius:8px 8px 0 0}.header h1{margin:0;font-size:24px}.content{padding:20px}.content p{margin:10px 0}.content a{display:inline-block;margin:20px 0;padding:10px 20px;background-color:#3F51B5;color:white;text-decoration:none;border-radius:4px}.footer{text-align:center;margin-top:20px;font-size:12px;color:#666}</style></head><body><div class="container"><div class="header"><h1>Your Monthly Newsletter</h1></div><div class="content"><p>Hi #user.name#,</p><p>Here\'s what\'s new this month:</p><ul><li>Feature Spotlight: Discover the latest updates to our service.</li><li>Success Stories: See how users like you are thriving.</li><li>Upcoming Events: Don\'t miss our next webinar!</li></ul><p>Stay tuned for more exciting news next month.</p><a href="#read.more.link#" target="_blank">Read More</a><p>Thank you for being part of our community!</p><p>The Team</p></div><div class="footer"><p>&copy; 2024 Our Company. All rights reserved.</p></div></div></body></html>',
  },
]
